added assets from robotec-agriculture-gem
RobotecAI/robotec-generic-assets pull request #4
Opened 2024-08-28 18:34 UTC by Jakub-Krakowiak

2024-08-29 13:33 UTC, pawelbudziszewski commented on RobotecSmallContainersAssets/NOTICE
```suggestion

Both "Football" models were obtained from PolyHaven (https://polyhaven.com/a/football) and have CC0 license.

The "Barrel" model was obtained from PolyHaven (https://polyhaven.com/a/Barrel_02) and it has CC0 license.

The "CardboardBox" model was obtained from PolyHaven (https://polyhaven.com/a/cardboard_box_01) and it has CC0 license.

```

2024-08-29 13:40 UTC, pawelbudziszewski commented
2 more things:

1. Rename `FootballInflated` to `Football`
2. Move the origin to the center of the ball. It will be easier to rotate it on the scene.

2024-09-12 12:58 UTC, jhanca-robotecai requested changes
- notice information should be reworked
- barrels should be cleaned
- football origins should be fixed

2024-09-12 12:58 UTC, jhanca-robotecai commented on RobotecSmallContainersAssets/Assets/Barrel/Models/Barrel.fbx
It looks like we have two barrels: a barrel and a plastic barrel.
![image](https://github.com/user-attachments/assets/a6ce5916-0a0f-45f9-b7c9-55c723ad8a44)

2024-09-12 13:02 UTC, jhanca-robotecai commented
> 2. Move the origin to the center of the ball. It will be easier to rotate it on the scene.

I disagree - this is against our agreement that we put the origin at the point that connects to the scene. I.e. the center of the bottom plane for objects that can be put on the ground or the center of the sidewall for objects that should be hung on a wall.

Ball with an origin in the center of it changes the position after spawning, as the collider of the ball interacts with the collider of the floor. This should not happen.

2024-09-12 13:06 UTC, pawelbudziszewski commented on RobotecSmallContainersAssets/Assets/Barrel/Models/Barrel.fbx
Two barrels mean more diversity. I'd leave them both. Named `PlasticBarrel1` and `PlasticBarrel2`

2024-09-12 13:09 UTC, Jakub-Krakowiak commented on RobotecSmallContainersAssets/Assets/Barrel/Models/Barrel.fbx
Maybe name the new one PlasticBarrelWithHandles

2024-09-12 13:14 UTC, pawelbudziszewski commented
> > 2. Move the origin to the center of the ball. It will be easier to rotate it on the scene.
> 
> I disagree - this is against our agreement that we put the origin at the point that connects to the scene. I.e. the center of the bottom plane for objects that can be put on the ground or the center of the sidewall for objects that should be hung on a wall.
> 
> Ball with an origin in the center of it changes the position after spawning, as the collider of the ball interacts with the collider of the floor. This should not happen.

The ball can rotate. In such cases, we can place the origin in the rotation center. Or at least this is my opinion.
The other thing is, that rotating the ball may give more visual diversity - it's much more convenient if the origin is in the center.
However if the origin in the center causes any issues when spawning, it should be moved to the bottom.

2024-09-12 14:02 UTC, jhanca-robotecai approved these changes
I fixed the problems I found during the code review, I do not have any more comments.

2024-09-12 15:04 UTC, jhanca-robotecai commented
> The ball can rotate. In such case, we can place the origin in the rotation center. Or at least this is my opinion.
> The other thing is, that rotating the ball may give more visual diversity - it's much more convenient if the origin is in the center.
> However if the origin in the center causes any issues when spawning, it should be moved to the bottom.

I moved it back to the bottom. I see your point in making it more diverse by rotating, but as long as we do not simulate a pool full of balls, we do not have to rotate them at all.

2024-09-13 16:40 UTC, pawelbudziszewski approved these changes
There was an inconsistency in barrel prefabs. No both are dynamic rigid bodies and have consistent names.
I also access accessibility dates to model URLs (in NOTOCEs)

2024-09-16 09:33 UTC, merged